export interface TriviaQuestion {
  question: string;
  options: [string, string, string, string];
  correctAnswer: number; // Index of the correct answer (0-3)
}

export interface TriviaCategory {
  label: string;
  questions: TriviaQuestion[];
}

export const triviaCategories = {
  ciencia: {
    label: '🔬 Ciência',
    questions: [
      // Physics
      { question: 'Qual é a velocidade da luz no vácuo?', options: ['300.000 km/s', '150.000 km/s', '450.000 km/s', '600.000 km/s'], correctAnswer: 0 },
      { question: 'Quem formulou a teoria da relatividade?', options: ['Albert Einstein', 'Isaac Newton', 'Nikola Tesla', 'Stephen Hawking'], correctAnswer: 0 },
      { question: 'O que mede a unidade Kelvin?', options: ['Temperatura', 'Pressão', 'Velocidade', 'Energia'], correctAnswer: 0 },
      { question: 'Qual é a força que mantém os planetas em órbita?', options: ['Gravidade', 'Magnetismo', 'Eletricidade', 'Pressão'], correctAnswer: 0 },
      { question: 'O que é um protão?', options: ['Partícula com carga positiva', 'Partícula com carga negativa', 'Partícula neutra', 'Tipo de energia'], correctAnswer: 0 },
      { question: 'Qual é a partícula subatómica sem carga elétrica?', options: ['Neutrão', 'Protão', 'Eletrão', 'Positrão'], correctAnswer: 0 },
      { question: 'O que estuda a termodinâmica?', options: ['Calor e temperatura', 'Luz', 'Som', 'Magnetismo'], correctAnswer: 0 },
      { question: 'Qual é a unidade de medida da força?', options: ['Newton', 'Joule', 'Watt', 'Pascal'], correctAnswer: 0 },
      { question: 'O que é a inércia?', options: ['Tendência de um corpo manter seu estado', 'Aceleração', 'Velocidade máxima', 'Força gravitacional'], correctAnswer: 0 },
      { question: 'Quantas leis de Newton existem?', options: ['Três', 'Duas', 'Quatro', 'Cinco'], correctAnswer: 0 },
      
      // Chemistry
      { question: 'Qual é o símbolo químico do ouro?', options: ['Au', 'Ag', 'Fe', 'Cu'], correctAnswer: 0 },
      { question: 'Qual é o elemento mais abundante no universo?', options: ['Hidrogénio', 'Hélio', 'Oxigénio', 'Carbono'], correctAnswer: 0 },
      { question: 'O que é H2O?', options: ['Água', 'Peróxido', 'Ácido', 'Base'], correctAnswer: 0 },
      { question: 'Qual é o pH da água pura?', options: ['7', '0', '14', '10'], correctAnswer: 0 },
      { question: 'O que é um ácido?', options: ['Substância que liberta H+', 'Substância que liberta OH-', 'Substância neutra', 'Substância radioativa'], correctAnswer: 0 },
      { question: 'Qual é o número atómico do carbono?', options: ['6', '12', '8', '14'], correctAnswer: 0 },
      { question: 'O que é uma ligação covalente?', options: ['Partilha de eletrões', 'Transferência de eletrões', 'Atração gravitacional', 'Repulsão magnética'], correctAnswer: 0 },
      { question: 'Qual é o gás mais abundante na atmosfera terrestre?', options: ['Azoto', 'Oxigénio', 'Dióxido de carbono', 'Árgon'], correctAnswer: 0 },
      { question: 'O que é a fotossíntese?', options: ['Produção de oxigénio pelas plantas', 'Respiração animal', 'Digestão', 'Evaporação'], correctAnswer: 0 },
      { question: 'Qual é a fórmula do sal comum?', options: ['NaCl', 'KCl', 'CaCl2', 'MgCl2'], correctAnswer: 0 },
      
      // Biology
      { question: 'Qual é a menor unidade da vida?', options: ['Célula', 'Átomo', 'Molécula', 'Órgão'], correctAnswer: 0 },
      { question: 'O que é o DNA?', options: ['Material genético', 'Proteína', 'Carboidrato', 'Lipídio'], correctAnswer: 0 },
      { question: 'Quantos cromossomas tem o ser humano?', options: ['46', '23', '48', '50'], correctAnswer: 0 },
      { question: 'Qual é o maior órgão do corpo humano?', options: ['Pele', 'Fígado', 'Cérebro', 'Coração'], correctAnswer: 0 },
      { question: 'O que são mitocôndrias?', options: ['Produtoras de energia celular', 'Armazenadoras de água', 'Produtoras de proteínas', 'Núcleo celular'], correctAnswer: 0 },
      { question: 'Qual é o sistema responsável pela respiração?', options: ['Sistema respiratório', 'Sistema digestivo', 'Sistema nervoso', 'Sistema circulatório'], correctAnswer: 0 },
      { question: 'O que é a hemoglobina?', options: ['Proteína do sangue', 'Hormona', 'Enzima digestiva', 'Vitamina'], correctAnswer: 0 },
      { question: 'Quantos ossos tem o corpo humano adulto?', options: ['206', '205', '207', '300'], correctAnswer: 0 },
      { question: 'O que é a fotossíntese realizada por?', options: ['Cloroplastos', 'Mitocôndrias', 'Ribossomas', 'Lisossomas'], correctAnswer: 0 },
      { question: 'Qual é o órgão que bombeia o sangue?', options: ['Coração', 'Pulmão', 'Fígado', 'Rim'], correctAnswer: 0 },
      
      // Astronomy
      { question: 'Qual é o planeta mais próximo do Sol?', options: ['Mercúrio', 'Vénus', 'Terra', 'Marte'], correctAnswer: 0 },
      { question: 'Qual é o maior planeta do Sistema Solar?', options: ['Júpiter', 'Saturno', 'Urano', 'Neptuno'], correctAnswer: 0 },
      { question: 'Quantos planetas tem o Sistema Solar?', options: ['8', '9', '7', '10'], correctAnswer: 0 },
      { question: 'O que é a Via Láctea?', options: ['Nossa galáxia', 'Um planeta', 'Uma estrela', 'Um cometa'], correctAnswer: 0 },
      { question: 'Qual é a estrela mais próxima da Terra?', options: ['Sol', 'Proxima Centauri', 'Sirius', 'Betelgeuse'], correctAnswer: 0 },
      { question: 'O que é um buraco negro?', options: ['Região com gravidade extrema', 'Planeta escuro', 'Estrela fria', 'Cometa'], correctAnswer: 0 },
      { question: 'Quanto tempo leva a luz do Sol a chegar à Terra?', options: ['8 minutos', '1 minuto', '1 hora', '1 dia'], correctAnswer: 0 },
      { question: 'Qual é o satélite natural da Terra?', options: ['Lua', 'Marte', 'Io', 'Europa'], correctAnswer: 0 },
      { question: 'O que são as estrelas cadentes?', options: ['Meteoritos', 'Estrelas a cair', 'Satélites', 'Cometas'], correctAnswer: 0 },
      { question: 'Qual planeta tem anéis visíveis?', options: ['Saturno', 'Júpiter', 'Marte', 'Mercúrio'], correctAnswer: 0 },
      
      // Earth Science
      { question: 'Qual é a camada mais externa da Terra?', options: ['Crosta', 'Manto', 'Núcleo', 'Atmosfera'], correctAnswer: 0 },
      { question: 'O que causa os terramotos?', options: ['Movimento de placas tectónicas', 'Vento forte', 'Chuva intensa', 'Marés'], correctAnswer: 0 },
      { question: 'Qual é o ponto mais alto da Terra?', options: ['Monte Everest', 'K2', 'Kilimanjaro', 'Monte Branco'], correctAnswer: 0 },
      { question: 'O que é o magma?', options: ['Rocha fundida', 'Água quente', 'Gás vulcânico', 'Minério'], correctAnswer: 0 },
      { question: 'Qual é o oceano maior?', options: ['Pacífico', 'Atlântico', 'Índico', 'Ártico'], correctAnswer: 0 },
      { question: 'O que mede a escala Richter?', options: ['Intensidade de terramotos', 'Temperatura', 'Velocidade do vento', 'Pressão atmosférica'], correctAnswer: 0 },
      { question: 'O que é o efeito de estufa?', options: ['Aquecimento da atmosfera', 'Arrefecimento global', 'Chuva ácida', 'Destruição do ozono'], correctAnswer: 0 },
      { question: 'Qual é a percentagem de água no planeta Terra?', options: ['71%', '50%', '85%', '60%'], correctAnswer: 0 },
      { question: 'O que são fósseis?', options: ['Restos de seres antigos', 'Rochas raras', 'Minerais', 'Cristais'], correctAnswer: 0 },
      { question: 'Qual é a camada que protege a Terra dos raios UV?', options: ['Ozono', 'Troposfera', 'Estratosfera', 'Ionosfera'], correctAnswer: 0 },
      
      // Technology
      { question: 'Quem inventou a lâmpada elétrica?', options: ['Thomas Edison', 'Nikola Tesla', 'Alexander Bell', 'Benjamin Franklin'], correctAnswer: 0 },
      { question: 'O que significa CPU?', options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Power Unit', 'Computer Processing Utility'], correctAnswer: 0 },
      { question: 'Qual foi o primeiro computador eletrónico?', options: ['ENIAC', 'Apple I', 'IBM PC', 'Commodore 64'], correctAnswer: 0 },
      { question: 'O que é um byte?', options: ['8 bits', '4 bits', '16 bits', '32 bits'], correctAnswer: 0 },
      { question: 'Quem fundou a Microsoft?', options: ['Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'Larry Page'], correctAnswer: 0 },
      { question: 'O que é HTML?', options: ['Linguagem de marcação', 'Linguagem de programação', 'Sistema operativo', 'Browser'], correctAnswer: 0 },
      { question: 'Qual é o sistema operativo do iPhone?', options: ['iOS', 'Android', 'Windows', 'Linux'], correctAnswer: 0 },
      { question: 'O que é IA?', options: ['Inteligência Artificial', 'Internet Avançada', 'Informação Automática', 'Interface Avançada'], correctAnswer: 0 },
      { question: 'Quem criou o Facebook?', options: ['Mark Zuckerberg', 'Jack Dorsey', 'Elon Musk', 'Jeff Bezos'], correctAnswer: 0 },
      { question: 'O que é RAM?', options: ['Memória de acesso aleatório', 'Disco rígido', 'Processador', 'Placa gráfica'], correctAnswer: 0 },
      
      // Mathematics
      { question: 'Quanto é π (pi) aproximadamente?', options: ['3.14', '2.71', '1.62', '4.20'], correctAnswer: 0 },
      { question: 'O que é um número primo?', options: ['Divisível apenas por 1 e ele mesmo', 'Número par', 'Número ímpar', 'Número negativo'], correctAnswer: 0 },
      { question: 'Quanto é 2 elevado a 10?', options: ['1024', '512', '2048', '256'], correctAnswer: 0 },
      { question: 'O que é a hipotenusa?', options: ['Lado oposto ao ângulo reto', 'Cateto menor', 'Ângulo agudo', 'Perímetro'], correctAnswer: 0 },
      { question: 'Qual é o valor de 0!  (fatorial)?', options: ['1', '0', 'Indefinido', 'Infinito'], correctAnswer: 0 },
      { question: 'O que é um polígono com 5 lados?', options: ['Pentágono', 'Hexágono', 'Heptágono', 'Octógono'], correctAnswer: 0 },
      { question: 'Qual é a raiz quadrada de 144?', options: ['12', '11', '13', '14'], correctAnswer: 0 },
      { question: 'O que é a sequência de Fibonacci?', options: ['Cada número é soma dos 2 anteriores', 'Números primos', 'Números pares', 'Números aleatórios'], correctAnswer: 0 },
      { question: 'Quantos graus tem um triângulo?', options: ['180', '360', '90', '270'], correctAnswer: 0 },
      { question: 'O que é o número de ouro?', options: ['1.618', '3.14', '2.71', '1.414'], correctAnswer: 0 },
      
      // Medicine
      { question: 'Qual é o grupo sanguíneo universal doador?', options: ['O-', 'AB+', 'O+', 'A-'], correctAnswer: 0 },
      { question: 'O que é a insulina?', options: ['Hormona que regula açúcar', 'Vitamina', 'Proteína muscular', 'Enzima digestiva'], correctAnswer: 0 },
      { question: 'Qual órgão produz a bile?', options: ['Fígado', 'Pâncreas', 'Estômago', 'Vesícula'], correctAnswer: 0 },
      { question: 'O que é a diabetes?', options: ['Doença do açúcar no sangue', 'Doença do coração', 'Doença dos pulmões', 'Doença dos rins'], correctAnswer: 0 },
      { question: 'Quantos dentes tem um adulto?', options: ['32', '28', '30', '36'], correctAnswer: 0 },
      { question: 'O que é a adrenalina?', options: ['Hormona do stress', 'Vitamina', 'Proteína', 'Mineral'], correctAnswer: 0 },
      { question: 'Qual é a temperatura normal do corpo?', options: ['36-37°C', '35-36°C', '37-38°C', '38-39°C'], correctAnswer: 0 },
      { question: 'O que causa a gripe?', options: ['Vírus', 'Bactéria', 'Fungo', 'Parasita'], correctAnswer: 0 },
      { question: 'Qual vitamina vem do sol?', options: ['Vitamina D', 'Vitamina C', 'Vitamina A', 'Vitamina E'], correctAnswer: 0 },
      { question: 'O que é a anemia?', options: ['Falta de ferro no sangue', 'Excesso de açúcar', 'Pressão alta', 'Doença óssea'], correctAnswer: 0 },
      
      // Environment
      { question: 'O que é a reciclagem?', options: ['Reutilizar materiais', 'Queimar lixo', 'Enterrar resíduos', 'Exportar lixo'], correctAnswer: 0 },
      { question: 'Qual gás causa o aquecimento global?', options: ['Dióxido de carbono', 'Oxigénio', 'Azoto', 'Hidrogénio'], correctAnswer: 0 },
      { question: 'O que são energias renováveis?', options: ['Que não se esgotam', 'Baratas', 'Poluentes', 'Raras'], correctAnswer: 0 },
      { question: 'Qual é a principal fonte de energia solar?', options: ['Sol', 'Vento', 'Água', 'Carvão'], correctAnswer: 0 },
      { question: 'O que é a desflorestação?', options: ['Destruição de florestas', 'Plantação de árvores', 'Cuidar da natureza', 'Reciclagem'], correctAnswer: 0 },
      { question: 'Quantos R tem a regra dos resíduos?', options: ['3 (Reduzir, Reutilizar, Reciclar)', '2', '4', '5'], correctAnswer: 0 },
      { question: 'O que é a camada de ozono?', options: ['Protege dos raios UV', 'Camada de água', 'Camada de ar', 'Camada de terra'], correctAnswer: 0 },
      { question: 'Qual animal está em extinção?', options: ['Panda', 'Cão', 'Gato', 'Rato'], correctAnswer: 0 },
      { question: 'O que é a poluição atmosférica?', options: ['Contaminação do ar', 'Limpeza do ar', 'Ar fresco', 'Vento forte'], correctAnswer: 0 },
      { question: 'Quanto tempo demora plástico a decompor?', options: ['Centenas de anos', '1 ano', '1 mês', '1 semana'], correctAnswer: 0 },
      
      // Genetics
      { question: 'Quem descobriu a estrutura do DNA?', options: ['Watson e Crick', 'Darwin', 'Mendel', 'Pasteur'], correctAnswer: 0 },
      { question: 'O que são genes?', options: ['Unidades de hereditariedade', 'Células', 'Proteínas', 'Vitaminas'], correctAnswer: 0 },
      { question: 'Quantos pares de cromossomas tem o humano?', options: ['23', '46', '22', '24'], correctAnswer: 0 },
      { question: 'O que é uma mutação?', options: ['Alteração no DNA', 'Doença', 'Vitamina', 'Proteína'], correctAnswer: 0 },
      { question: 'Quem foi Gregor Mendel?', options: ['Pai da genética', 'Inventor', 'Médico', 'Químico'], correctAnswer: 0 },
      { question: 'O que determina o sexo biológico?', options: ['Cromossomas X e Y', 'Hormónios', 'Proteínas', 'Vitaminas'], correctAnswer: 0 },
      { question: 'O que é clonagem?', options: ['Cópia genética', 'Cirurgia', 'Medicamento', 'Vacina'], correctAnswer: 0 },
      { question: 'O que é RNA?', options: ['Ácido ribonucleico', 'Proteína', 'Hormona', 'Enzima'], correctAnswer: 0 },
      { question: 'O que é genoma?', options: ['Conjunto completo de genes', 'Célula', 'Tecido', 'Órgão'], correctAnswer: 0 },
      { question: 'O que são gémeos idênticos?', options: ['Mesmo DNA', 'Irmãos normais', 'Mesma idade', 'Mesmo género'], correctAnswer: 0 },
      
      // Paleontology
      { question: 'Quando viveram os dinossauros?', options: ['Era Mesozoica', 'Era Cenozoica', 'Era Paleozoica', 'Era atual'], correctAnswer: 0 },
      { question: 'O que causou extinção dos dinossauros?', options: ['Impacto de asteroide', 'Idade', 'Doenças', 'Fome'], correctAnswer: 0 },
      { question: 'Qual era o maior dinossauro?', options: ['Argentinossauro', 'T-Rex', 'Velociraptor', 'Tricerátops'], correctAnswer: 0 },
      { question: 'O que é um fóssil?', options: ['Resto preservado de organismo', 'Rocha', 'Mineral', 'Cristal'], correctAnswer: 0 },
      { question: 'Que animal moderno descende dos dinossauros?', options: ['Aves', 'Mamíferos', 'Répteis', 'Peixes'], correctAnswer: 0 },
      { question: 'Há quantos anos existiram dinossauros?', options: ['65-230 milhões de anos', '1 milhão', '1000 anos', '10.000 anos'], correctAnswer: 0 },
      { question: 'O que comia o T-Rex?', options: ['Carne', 'Plantas', 'Peixe', 'Insetos'], correctAnswer: 0 },
      { question: 'Qual dinossauro tinha 3 chifres?', options: ['Tricerátops', 'T-Rex', 'Diplodoco', 'Estegossauro'], correctAnswer: 0 },
      { question: 'O que é paleontologia?', options: ['Estudo de fósseis', 'Estudo de rochas', 'Estudo de plantas', 'Estudo de animais'], correctAnswer: 0 },
      { question: 'Qual dinossauro voava?', options: ['Pterodáctilo', 'T-Rex', 'Braquiossauro', 'Anquilossauro'], correctAnswer: 0 },
      
      // Weather & Climate
      { question: 'O que é um furacão?', options: ['Tempestade tropical intensa', 'Vento fraco', 'Chuva leve', 'Neve'], correctAnswer: 0 },
      { question: 'O que mede o barómetro?', options: ['Pressão atmosférica', 'Temperatura', 'Humidade', 'Velocidade vento'], correctAnswer: 0 },
      { question: 'O que é a precipitação?', options: ['Chuva, neve, granizo', 'Vento', 'Sol', 'Nuvens'], correctAnswer: 0 },
      { question: 'O que causa o arco-íris?', options: ['Refração da luz', 'Poluição', 'Vento', 'Temperatura'], correctAnswer: 0 },
      { question: 'Qual é a temperatura mais baixa possível?', options: ['-273°C (zero absoluto)', '-100°C', '-200°C', '-500°C'], correctAnswer: 0 },
      { question: 'O que é a evaporação?', options: ['Água vira vapor', 'Água congela', 'Chuva cai', 'Neve derrete'], correctAnswer: 0 },
      { question: 'O que forma as nuvens?', options: ['Vapor de água', 'Fumo', 'Poeira', 'Gás'], correctAnswer: 0 },
      { question: 'O que é um tornado?', options: ['Coluna de ar em rotação', 'Chuva forte', 'Vento fraco', 'Neve'], correctAnswer: 0 },
      { question: 'Qual é o deserto mais quente?', options: ['Saara', 'Gobi', 'Kalahari', 'Atacama'], correctAnswer: 0 },
      { question: 'O que é condensação?', options: ['Vapor vira água', 'Água vira gelo', 'Gelo vira água', 'Água vira vapor'], correctAnswer: 0 },
      
      // Energy
      { question: 'O que é energia cinética?', options: ['Energia de movimento', 'Energia parada', 'Energia química', 'Energia nuclear'], correctAnswer: 0 },
      { question: 'O que é uma fonte de energia renovável?', options: ['Solar', 'Carvão', 'Petróleo', 'Gás natural'], correctAnswer: 0 },
      { question: 'O que transforma vento em eletricidade?', options: ['Turbina eólica', 'Painel solar', 'Barragem', 'Central nuclear'], correctAnswer: 0 },
      { question: 'O que é energia potencial?', options: ['Energia armazenada', 'Energia em movimento', 'Energia perdida', 'Energia criada'], correctAnswer: 0 },
      { question: 'Qual unidade mede energia?', options: ['Joule', 'Newton', 'Watt', 'Volt'], correctAnswer: 0 },
      { question: 'O que é fotovoltaico?', options: ['Converte luz em eletricidade', 'Armazena energia', 'Queima combustível', 'Usa vento'], correctAnswer: 0 },
      { question: 'O que é uma bateria?', options: ['Armazena energia química', 'Produz energia', 'Destrói energia', 'Transforma luz'], correctAnswer: 0 },
      { question: 'O que é energia térmica?', options: ['Energia de calor', 'Energia de movimento', 'Energia elétrica', 'Energia nuclear'], correctAnswer: 0 },
      { question: 'O que produz energia nuclear?', options: ['Fissão atómica', 'Queima de carvão', 'Vento', 'Água'], correctAnswer: 0 },
      { question: 'Qual lei diz que energia não se cria nem destrói?', options: ['Conservação da energia', 'Gravidade', 'Inercia', 'Ação e reação'], correctAnswer: 0 },
      
      // Additional Science Questions
      { question: 'O que é um eclipse solar?', options: ['Lua bloqueia o Sol', 'Sol bloqueia Lua', 'Terra bloqueia Sol', 'Marte bloqueia Sol'], correctAnswer: 0 },
      { question: 'Qual é o metal mais abundante na Terra?', options: ['Alumínio', 'Ferro', 'Cobre', 'Ouro'], correctAnswer: 0 },
      { question: 'O que é a pressão atmosférica?', options: ['Peso do ar', 'Temperatura', 'Humidade', 'Vento'], correctAnswer: 0 },
      { question: 'Quantos estados da matéria existem?', options: ['4 principais', '2', '3', '5'], correctAnswer: 0 },
      { question: 'O que é sublimação?', options: ['Sólido vira gás', 'Líquido vira gás', 'Gás vira líquido', 'Sólido vira líquido'], correctAnswer: 0 },
      { question: 'Qual parte da célula controla suas atividades?', options: ['Núcleo', 'Citoplasma', 'Membrana', 'Parede'], correctAnswer: 0 },
      { question: 'O que é um antibiótico?', options: ['Mata bactérias', 'Mata vírus', 'Mata fungos', 'Mata todos'], correctAnswer: 0 },
      { question: 'Qual sentido detecta sabores?', options: ['Paladar', 'Olfato', 'Visão', 'Audição'], correctAnswer: 0 },
      { question: 'O que é a biodiversidade?', options: ['Variedade de vida', 'Poluição', 'Extinção', 'Clima'], correctAnswer: 0 },
      { question: 'Qual é o gás que respiramos?', options: ['Oxigénio', 'Azoto', 'Dióxido de carbono', 'Hélio'], correctAnswer: 0 },
    ],
  } as TriviaCategory,

  culturaArte: {
    label: '🎨 Cultura e Arte',
    questions: [
      // Pintura
      { question: 'Quem pintou a Mona Lisa?', options: ['Leonardo da Vinci', 'Michelangelo', 'Rafael', 'Donatello'], correctAnswer: 0 },
      { question: 'Qual é o movimento artístico de Pablo Picasso?', options: ['Cubismo', 'Impressionismo', 'Surrealismo', 'Realismo'], correctAnswer: 0 },
      { question: 'Onde está a Capela Sistina?', options: ['Vaticano', 'Paris', 'Londres', 'Madrid'], correctAnswer: 0 },
      { question: 'Quem pintou A Noite Estrelada?', options: ['Van Gogh', 'Monet', 'Renoir', 'Degas'], correctAnswer: 0 },
      { question: 'O que significa Renascimento?', options: ['Renascer da cultura clássica', 'Arte religiosa', 'Arte moderna', 'Arte abstrata'], correctAnswer: 0 },
      { question: 'Quem pintou o teto da Capela Sistina?', options: ['Michelangelo', 'Leonardo', 'Rafael', 'Botticelli'], correctAnswer: 0 },
      { question: 'Qual movimento valorizava a luz e cor?', options: ['Impressionismo', 'Cubismo', 'Dadaísmo', 'Futurismo'], correctAnswer: 0 },
      { question: 'Quem pintou Guernica?', options: ['Picasso', 'Dalí', 'Miró', 'Goya'], correctAnswer: 0 },
      { question: 'O que é um afresco?', options: ['Pintura em parede húmida', 'Pintura a óleo', 'Escultura', 'Gravura'], correctAnswer: 0 },
      { question: 'Quem pintou O Grito?', options: ['Munch', 'Van Gogh', 'Klimt', 'Kandinsky'], correctAnswer: 0 },
      // Escultura
      { question: 'Quem esculpiu David?', options: ['Michelangelo', 'Donatello', 'Bernini', 'Rodin'], correctAnswer: 0 },
      { question: 'Onde está a estátua da Liberdade?', options: ['Nova Iorque', 'Paris', 'Londres', 'Roma'], correctAnswer: 0 },
      { question: 'O que é mármore?', options: ['Pedra para escultura', 'Madeira', 'Metal', 'Argila'], correctAnswer: 0 },
      { question: 'Quem esculpiu O Pensador?', options: ['Rodin', 'Michelangelo', 'Bernini', 'Canova'], correctAnswer: 0 },
      { question: 'O que é escultura de bronze?', options: ['Fundição em metal', 'Talha em pedra', 'Moldagem em barro', 'Corte em madeira'], correctAnswer: 0 },
      // Música
      { question: 'Quem compôs Für Elise?', options: ['Beethoven', 'Mozart', 'Bach', 'Chopin'], correctAnswer: 0 },
      { question: 'Quantas sinfonias compôs Beethoven?', options: ['9', '5', '10', '7'], correctAnswer: 0 },
      { question: 'O que é uma ópera?', options: ['Teatro musical', 'Dança', 'Pintura', 'Escultura'], correctAnswer: 0 },
      { question: 'Quem compôs As Quatro Estações?', options: ['Vivaldi', 'Bach', 'Handel', 'Scarlatti'], correctAnswer: 0 },
      { question: 'O que é um maestro?', options: ['Condutor de orquestra', 'Cantor', 'Compositor', 'Pianista'], correctAnswer: 0 },
      { question: 'Quantas teclas tem um piano?', options: ['88', '72', '100', '64'], correctAnswer: 0 },
      { question: 'Qual instrumento tocava Mozart?', options: ['Piano', 'Violino apenas', 'Flauta apenas', 'Guitarra'], correctAnswer: 0 },
      { question: 'O que é a sinfonia?', options: ['Obra para orquestra', 'Solo de piano', 'Canto coral', 'Dança'], correctAnswer: 0 },
      { question: 'Quem compôs o Réquiem?', options: ['Mozart', 'Bach', 'Handel', 'Haydn'], correctAnswer: 0 },
      { question: 'O que é uma sonata?', options: ['Peça musical', 'Instrumento', 'Dança', 'Teatro'], correctAnswer: 0 },
      // Cinema
      { question: 'Quem dirigiu E.T.?', options: ['Spielberg', 'Lucas', 'Scorsese', 'Coppola'], correctAnswer: 0 },
      { question: 'Quem interpretou Jack em Titanic?', options: ['DiCaprio', 'Brad Pitt', 'Tom Cruise', 'Johnny Depp'], correctAnswer: 0 },
      { question: 'Qual é o primeiro filme sonoro?', options: ['O Cantor de Jazz', 'Cidadão Kane', 'Casablanca', 'E Tudo o Vento Levou'], correctAnswer: 0 },
      { question: 'Quem dirigiu O Padrinho?', options: ['Coppola', 'Scorsese', 'Tarantino', 'Kubrick'], correctAnswer: 0 },
      { question: 'Que animal é Simba?', options: ['Leão', 'Tigre', 'Urso', 'Leopardo'], correctAnswer: 0 },
      { question: 'Quem criou Star Wars?', options: ['George Lucas', 'Spielberg', 'Cameron', 'Zemeckis'], correctAnswer: 0 },
      { question: 'Qual é a saga de Harry Potter?', options: ['8 filmes', '7 filmes', '9 filmes', '10 filmes'], correctAnswer: 0 },
      { question: 'Quem é o Homem de Ferro?', options: ['Tony Stark', 'Bruce Wayne', 'Peter Parker', 'Steve Rogers'], correctAnswer: 0 },
      { question: 'Onde se passa Casablanca?', options: ['Marrocos', 'França', 'Itália', 'Espanha'], correctAnswer: 0 },
      // Teatro
      { question: 'Quem escreveu Romeu e Julieta?', options: ['Shakespeare', 'Molière', 'Sófocles', 'Eurípides'], correctAnswer: 0 },
      { question: 'O que é uma tragédia?', options: ['Drama com fim triste', 'Comédia', 'Musical', 'Dança'], correctAnswer: 0 },
      { question: 'Quem escreveu Hamlet?', options: ['Shakespeare', 'Marlowe', 'Jonson', 'Webster'], correctAnswer: 0 },
      { question: 'O que é um monólogo?', options: ['Fala sozinho', 'Diálogo', 'Coro', 'Narração'], correctAnswer: 0 },
      { question: 'Onde nasceu o teatro?', options: ['Grécia Antiga', 'Roma', 'França', 'Inglaterra'], correctAnswer: 0 },
      // Literatura
      { question: 'Quem escreveu Os Lusíadas?', options: ['Camões', 'Pessoa', 'Saramago', 'Eça'], correctAnswer: 0 },
      { question: 'Quantos cantos têm Os Lusíadas?', options: ['10', '12', '8', '15'], correctAnswer: 0 },
      { question: 'Quem escreveu Dom Quixote?', options: ['Cervantes', 'Lope de Vega', 'Calderón', 'Góngora'], correctAnswer: 0 },
      { question: 'O que é um soneto?', options: ['Poema de 14 versos', 'Conto', 'Romance', 'Novela'], correctAnswer: 0 },
      { question: 'Quem criou Sherlock Holmes?', options: ['Conan Doyle', 'Agatha Christie', 'Edgar Allan Poe', 'Dashiell Hammett'], correctAnswer: 0 },
      // Arquitetura
      { question: 'Quem projetou a Torre Eiffel?', options: ['Gustave Eiffel', 'Le Corbusier', 'Gaudí', 'Wright'], correctAnswer: 0 },
      { question: 'Onde fica a Sagrada Família?', options: ['Barcelona', 'Madrid', 'Lisboa', 'Roma'], correctAnswer: 0 },
      { question: 'O que é arquitetura gótica?', options: ['Estilo medieval', 'Estilo moderno', 'Estilo clássico', 'Estilo barroco'], correctAnswer: 0 },
      { question: 'Quem projetou a Sagrada Família?', options: ['Gaudí', 'Eiffel', 'Niemeyer', 'Gehry'], correctAnswer: 0 },
      { question: 'O que é uma cúpula?', options: ['Teto redondo', 'Torre', 'Coluna', 'Porta'], correctAnswer: 0 },
      // Dança
      { question: 'O que é ballet?', options: ['Dança clássica', 'Dança moderna', 'Dança de salão', 'Dança folclórica'], correctAnswer: 0 },
      { question: 'De onde é o flamenco?', options: ['Espanha', 'Portugal', 'França', 'Itália'], correctAnswer: 0 },
      { question: 'O que é uma pirueta?', options: ['Giro no ballet', 'Salto', 'Passo', 'Pose'], correctAnswer: 0 },
      { question: 'Onde surgiu o tango?', options: ['Argentina', 'Brasil', 'Cuba', 'México'], correctAnswer: 0 },
      { question: 'O que calçam bailarinas?', options: ['Sapatilhas de ponta', 'Tênis', 'Sandálias', 'Botas'], correctAnswer: 0 },
    ],
  } as TriviaCategory,

  literatura: {
    label: '📚 Literatura',
    questions: [
      // Clássicos Portugueses
      { question: 'Quem escreveu Os Maias?', options: ['Eça de Queirós', 'Camilo Castelo Branco', 'Camões', 'Garrett'], correctAnswer: 0 },
      { question: 'Quem escreveu Mensagem?', options: ['Fernando Pessoa', 'Camões', 'Florbela Espanca', 'Sophia'], correctAnswer: 0 },
      { question: 'Quantos heterónimos tinha Pessoa?', options: ['Vários (principais: 3)', '1', '2', '5'], correctAnswer: 0 },
      { question: 'Quem é Álvaro de Campos?', options: ['Heterónimo de Pessoa', 'Poeta real', 'Personagem', 'Escritor'], correctAnswer: 0 },
      { question: 'Quem escreveu Amor de Perdição?', options: ['Camilo Castelo Branco', 'Eça de Queirós', 'Garrett', 'Herculano'], correctAnswer: 0 },
      { question: 'O que é Memorial do Convento?', options: ['Romance de Saramago', 'Poesia', 'Teatro', 'Conto'], correctAnswer: 0 },
      { question: 'Quem ganhou Nobel da Literatura português?', options: ['José Saramago', 'Fernando Pessoa', 'Eça de Queirós', 'Camões'], correctAnswer: 0 },
      { question: 'O que narra Os Lusíadas?', options: ['Descobrimentos portugueses', 'Amor', 'Guerra', 'Vida rural'], correctAnswer: 0 },
      { question: 'Quem é Vasco da Gama n Os Lusíadas?', options: ['Herói navegador', 'Vilão', 'Poeta', 'Rei'], correctAnswer: 0 },
      { question: 'O que é Frei Luís de Sousa?', options: ['Teatro de Garrett', 'Romance', 'Poesia', 'Ensaio'], correctAnswer: 0 },
      // Clássicos Mundiais
      { question: 'Quem escreveu 1984?', options: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H.G. Wells'], correctAnswer: 0 },
      { question: 'Onde se passa Romeu e Julieta?', options: ['Verona', 'Veneza', 'Roma', 'Florença'], correctAnswer: 0 },
      { question: 'Quem escreveu Guerra e Paz?', options: ['Tolstói', 'Dostoiévski', 'Chekhov', 'Turgueniev'], correctAnswer: 0 },
      { question: 'Quem criou Tarzan?', options: ['Edgar Rice Burroughs', 'Kipling', 'London', 'Stevenson'], correctAnswer: 0 },
      { question: 'Quem escreveu O Principezinho?', options: ['Saint-Exupéry', 'Andersen', 'Grimm', 'Perrault'], correctAnswer: 0 },
      { question: 'De onde é Don Quixote?', options: ['La Mancha, Espanha', 'Portugal', 'França', 'Itália'], correctAnswer: 0 },
      { question: 'Quem escreveu Odisseia?', options: ['Homero', 'Virgílio', 'Ovídio', 'Sófocles'], correctAnswer: 0 },
      { question: 'O que procurava Dom Quixote?', options: ['Aventuras de cavaleiro', 'Tesouro', 'Amor', 'Fama'], correctAnswer: 0 },
      { question: 'Quem escreveu Crime e Castigo?', options: ['Dostoiévski', 'Tolstói', 'Gogol', 'Pushkin'], correctAnswer: 0 },
      // Autores Famosos
      { question: 'Quem escreveu Harry Potter?', options: ['J.K. Rowling', 'Tolkien', 'Lewis', 'Pullman'], correctAnswer: 0 },
      { question: 'Quem criou Senhor dos Anéis?', options: ['J.R.R. Tolkien', 'C.S. Lewis', 'George Martin', 'Rowling'], correctAnswer: 0 },
      { question: 'Quem escreveu sobre Sherlock Holmes?', options: ['Conan Doyle', 'Agatha Christie', 'Dorothy Sayers', 'Poe'], correctAnswer: 0 },
      { question: 'Quem criou Hercule Poirot?', options: ['Agatha Christie', 'Doyle', 'Chandler', 'Hammett'], correctAnswer: 0 },
      { question: 'Quem escreveu O Corvo?', options: ['Edgar Allan Poe', 'Lovecraft', 'King', 'Shelley'], correctAnswer: 0 },
      { question: 'Quem escreveu Frankenstein?', options: ['Mary Shelley', 'Bram Stoker', 'Poe', 'Lovecraft'], correctAnswer: 0 },
      { question: 'Quem escreveu Drácula?', options: ['Bram Stoker', 'Mary Shelley', 'Poe', 'Rice'], correctAnswer: 0 },
      { question: 'Quem escreveu sobre Maigret?', options: ['Georges Simenon', 'Christie', 'Doyle', 'Chandler'], correctAnswer: 0 },
      { question: 'Quem criou James Bond?', options: ['Ian Fleming', 'Le Carré', 'Deighton', 'Ludlum'], correctAnswer: 0 },
      { question: 'Quem escreveu Cem Anos de Solidão?', options: ['García Márquez', 'Borges', 'Cortázar', 'Vargas Llosa'], correctAnswer: 0 },
      // Géneros Literários
      { question: 'O que é uma biografia?', options: ['História de vida real', 'Ficção', 'Poesia', 'Teatro'], correctAnswer: 0 },
      { question: 'O que é ficção científica?', options: ['Futuro e tecnologia', 'Romance', 'Terror', 'Mistério'], correctAnswer: 0 },
      { question: 'O que é um romance?', options: ['Narrativa longa', 'Poesia', 'Teatro', 'Conto'], correctAnswer: 0 },
      { question: 'O que é poesia?', options: ['Texto em verso', 'Prosa', 'Drama', 'Ensaio'], correctAnswer: 0 },
      { question: 'O que é uma fábula?', options: ['História com moral', 'Romance', 'Poesia', 'Biografia'], correctAnswer: 0 },
      { question: 'O que é teatro?', options: ['Texto para representar', 'Poesia', 'Romance', 'Ensaio'], correctAnswer: 0 },
      { question: 'O que é um conto?', options: ['Narrativa curta', 'Romance', 'Poesia', 'Teatro'], correctAnswer: 0 },
      { question: 'O que é épico?', options: ['Poema heroico', 'Romance', 'Conto', 'Drama'], correctAnswer: 0 },
      { question: 'O que é sátira?', options: ['Crítica com humor', 'Tragédia', 'Romance', 'Epopeia'], correctAnswer: 0 },
      { question: 'O que é autobiografia?', options: ['Própria história de vida', 'Biografia de outro', 'Ficção', 'Poesia'], correctAnswer: 0 },
      // Personagens Famosas
      { question: 'Quem é o Capitão Ahab?', options: ['Caçador de baleia', 'Pirata', 'Explorador', 'Marinheiro'], correctAnswer: 0 },
      { question: 'Quem é Sancho Pança?', options: ['Escudeiro de Dom Quixote', 'Cavaleiro', 'Rei', 'Mago'], correctAnswer: 0 },
      { question: 'Quem é Gandalf?', options: ['Mago do Senhor dos Anéis', 'Hobbit', 'Elfo', 'Anão'], correctAnswer: 0 },
      { question: 'Quem é Quasímodo?', options: ['Corcunda de Notre-Dame', 'Príncipe', 'Cavaleiro', 'Ladrão'], correctAnswer: 0 },
      { question: 'Quem é Long John Silver?', options: ['Pirata de A Ilha do Tesouro', 'Marinheiro', 'Capitão', 'Explorador'], correctAnswer: 0 },
      { question: 'Quem é Jane Eyre?', options: ['Protagonista de romance', 'Rainha', 'Espia', 'Atriz'], correctAnswer: 0 },
      { question: 'Quem é Ebenezer Scrooge?', options: ['Avarento de Dickens', 'Detetive', 'Médico', 'Advogado'], correctAnswer: 0 },
      { question: 'Quem é Robinson Crusoé?', options: ['Náufrago em ilha', 'Pirata', 'Explorador', 'Soldado'], correctAnswer: 0 },
      { question: 'Quem é Anna Karenina?', options: ['Personagem de Tolstói', 'Rainha', 'Poeta', 'Atriz'], correctAnswer: 0 },
    ],
  } as TriviaCategory,

  historia: {
    label: '🏛️ História',
    questions: [
      { question: 'Quando foi fundado Portugal?', options: ['1143', '1500', '1000', '1200'], correctAnswer: 0 },
      { question: 'Quem foi o primeiro rei de Portugal?', options: ['D. Afonso Henriques', 'D. Dinis', 'D. João I', 'D. Manuel I'], correctAnswer: 0 },
      { question: 'Em que ano foi a Revolução de 25 de Abril?', options: ['1974', '1970', '1980', '1968'], correctAnswer: 0 },
      { question: 'Quem descobriu o caminho marítimo para a Índia?', options: ['Vasco da Gama', 'Cabral', 'Colombo', 'Magalhães'], correctAnswer: 0 },
      { question: 'Quando foi descoberto o Brasil?', options: ['1500', '1492', '1510', '1498'], correctAnswer: 0 },
      { question: 'Quem descobriu o Brasil?', options: ['Pedro Álvares Cabral', 'Vasco da Gama', 'Colombo', 'Magalhães'], correctAnswer: 0 },
      { question: 'Qual rei morreu em Alcácer Quibir?', options: ['D. Sebastião', 'D. Afonso V', 'D. Manuel I', 'D. João II'], correctAnswer: 0 },
      { question: 'Quando foi o Terramoto de Lisboa?', options: ['1755', '1800', '1700', '1750'], correctAnswer: 0 },
      { question: 'Quem foi Marquês de Pombal?', options: ['Ministro de D. José I', 'Rei', 'Navegador', 'Papa'], correctAnswer: 0 },
      { question: 'Quando terminou a monarquia em Portugal?', options: ['1910', '1920', '1900', '1889'], correctAnswer: 0 },
      { question: 'Qual foi a última rainha de Portugal?', options: ['D. Amélia', 'D. Maria I', 'D. Maria II', 'D. Catarina'], correctAnswer: 0 },
      { question: 'Quando Portugal entrou na UE?', options: ['1986', '1990', '1980', '1975'], correctAnswer: 0 },
      { question: 'Quem foi o ditador do Estado Novo?', options: ['Salazar', 'Carmona', 'Caetano', 'Sidónio'], correctAnswer: 0 },
      { question: 'O que foram as Invasões Francesas?', options: ['Napoleão invadiu Portugal', 'Guerra civil', 'Descobrimentos', 'Revolução'], correctAnswer: 0 },
      { question: 'Quem liderou a Restauração de 1640?', options: ['D. João IV', 'D. Afonso VI', 'D. Pedro II', 'D. João V'], correctAnswer: 0 },
      { question: 'Em que ano começou a II Guerra Mundial?', options: ['1939', '1940', '1938', '1941'], correctAnswer: 0 },
      { question: 'Quem foi Júlio César?', options: ['Imperador romano', 'Rei grego', 'Faraó egípcio', 'General persa'], correctAnswer: 0 },
      { question: 'Onde ficavam as pirâmides?', options: ['Egito', 'México', 'China', 'Grécia'], correctAnswer: 0 },
      { question: 'Quem foi Napoleão Bonaparte?', options: ['Imperador francês', 'Rei inglês', 'Papa', 'Filósofo'], correctAnswer: 0 },
      { question: 'Em que ano caiu o Muro de Berlim?', options: ['1989', '1990', '1985', '1991'], correctAnswer: 0 },
      { question: 'Quem descobriu a América?', options: ['Cristóvão Colombo', 'Vasco da Gama', 'Cabral', 'Magalhães'], correctAnswer: 0 },
      { question: 'Em que ano foi a Revolução Francesa?', options: ['1789', '1800', '1776', '1792'], correctAnswer: 0 },
      { question: 'Quem foi Cleópatra?', options: ['Rainha do Egito', 'Imperatriz romana', 'Deusa grega', 'Faraó'], correctAnswer: 0 },
      { question: 'O que foi a Guerra Fria?', options: ['Tensão EUA-URSS', 'Guerra no Ártico', 'Guerra na Ásia', 'Guerra civil'], correctAnswer: 0 },
      { question: 'Quem foi Alexandre, o Grande?', options: ['Conquistador macedónio', 'Imperador romano', 'Faraó', 'Rei persa'], correctAnswer: 0 },
      { question: 'Em que século foi a Idade Média?', options: ['V-XV', 'I-V', 'XV-XX', 'X-XV'], correctAnswer: 0 },
      { question: 'O que foram as Cruzadas?', options: ['Guerras religiosas', 'Descobrimentos', 'Revoluções', 'Invasões'], correctAnswer: 0 },
      { question: 'Quem foi Martin Luther King?', options: ['Ativista direitos civis', 'Presidente', 'Pastor', 'Músico'], correctAnswer: 0 },
      { question: 'O que foi o Holocausto?', options: ['Genocídio judeu', 'Guerra', 'Revolução', 'Tratado'], correctAnswer: 0 },
      { question: 'Quem foi Gandhi?', options: ['Líder indiano pacifista', 'Rei', 'Imperador', 'General'], correctAnswer: 0 },
      { question: 'Onde ficava a Grécia Antiga?', options: ['Mediterrâneo', 'Ásia', 'África', 'América'], correctAnswer: 0 },
      { question: 'Quem eram os faraós?', options: ['Reis do Egito', 'Deuses', 'Escravos', 'Soldados'], correctAnswer: 0 },
      { question: 'O que é uma múmia?', options: ['Corpo preservado', 'Estátua', 'Templo', 'Túmulo'], correctAnswer: 0 },
      { question: 'Quem construiu as pirâmides?', options: ['Egípcios', 'Gregos', 'Romanos', 'Maias'], correctAnswer: 0 },
      { question: 'O que é o Coliseu?', options: ['Anfiteatro romano', 'Templo grego', 'Pirâmide', 'Palácio'], correctAnswer: 0 },
      { question: 'Onde viviam os vikings?', options: ['Escandinávia', 'Grécia', 'Roma', 'Egito'], correctAnswer: 0 },
      { question: 'O que eram gladiadores?', options: ['Lutadores em arena', 'Soldados', 'Escravos', 'Reis'], correctAnswer: 0 },
      { question: 'Quem deu a primeira volta ao mundo?', options: ['Magalhães/Elcano', 'Colombo', 'Vasco da Gama', 'Cabral'], correctAnswer: 0 },
      { question: 'Para onde ia Colombo?', options: ['Índia', 'América', 'África', 'China'], correctAnswer: 0 },
      { question: 'Onde foi a Batalha de Aljubarrota?', options: ['Portugal', 'Espanha', 'França', 'Inglaterra'], correctAnswer: 0 },
    ],
  } as TriviaCategory,

  geografia: {
    label: '🌍 Geografia',
    questions: [
      { question: 'Qual é a capital de França?', options: ['Paris', 'Lyon', 'Marselha', 'Nice'], correctAnswer: 0 },
      { question: 'Qual é a capital de Itália?', options: ['Roma', 'Milão', 'Veneza', 'Florença'], correctAnswer: 0 },
      { question: 'Qual é a capital de Espanha?', options: ['Madrid', 'Barcelona', 'Sevilha', 'Valência'], correctAnswer: 0 },
      { question: 'Qual é a capital do Brasil?', options: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'], correctAnswer: 0 },
      { question: 'Qual é a capital dos EUA?', options: ['Washington D.C.', 'Nova Iorque', 'Los Angeles', 'Chicago'], correctAnswer: 0 },
      { question: 'Qual é a capital de Inglaterra?', options: ['Londres', 'Manchester', 'Liverpool', 'Birmingham'], correctAnswer: 0 },
      { question: 'Qual é a capital da Alemanha?', options: ['Berlim', 'Munique', 'Hamburgo', 'Frankfurt'], correctAnswer: 0 },
      { question: 'Qual é a capital do Japão?', options: ['Tóquio', 'Osaka', 'Quioto', 'Yokohama'], correctAnswer: 0 },
      { question: 'Qual é a capital da China?', options: ['Pequim', 'Xangai', 'Hong Kong', 'Cantão'], correctAnswer: 0 },
      { question: 'Qual é a capital da Rússia?', options: ['Moscovo', 'São Petersburgo', 'Kiev', 'Volgograd'], correctAnswer: 0 },
      { question: 'Qual é a capital da Austrália?', options: ['Camberra', 'Sydney', 'Melbourne', 'Brisbane'], correctAnswer: 0 },
      { question: 'Qual é a capital do Canadá?', options: ['Otava', 'Toronto', 'Montreal', 'Vancouver'], correctAnswer: 0 },
      { question: 'Qual é a capital do Egito?', options: ['Cairo', 'Alexandria', 'Luxor', 'Assuão'], correctAnswer: 0 },
      { question: 'Qual é a capital da Grécia?', options: ['Atenas', 'Salónica', 'Patras', 'Creta'], correctAnswer: 0 },
      { question: 'Qual é a capital da Argentina?', options: ['Buenos Aires', 'Córdoba', 'Rosário', 'Mendoza'], correctAnswer: 0 },
      { question: 'Qual é o maior país do mundo?', options: ['Rússia', 'Canadá', 'China', 'EUA'], correctAnswer: 0 },
      { question: 'Qual é o país mais populoso?', options: ['China', 'Índia', 'EUA', 'Indonésia'], correctAnswer: 0 },
      { question: 'Onde fica o Monte Everest?', options: ['Nepal/China', 'Índia', 'Paquistão', 'Butão'], correctAnswer: 0 },
      { question: 'Onde fica Machu Picchu?', options: ['Peru', 'Brasil', 'México', 'Bolívia'], correctAnswer: 0 },
      { question: 'Qual é o menor país do mundo?', options: ['Vaticano', 'Mónaco', 'San Marino', 'Liechtenstein'], correctAnswer: 0 },
      { question: 'Em que continente fica o Saara?', options: ['África', 'Ásia', 'América', 'Oceânia'], correctAnswer: 0 },
      { question: 'Onde fica a Torre Eiffel?', options: ['Paris', 'Londres', 'Roma', 'Berlim'], correctAnswer: 0 },
      { question: 'Qual país tem forma de bota?', options: ['Itália', 'Espanha', 'Grécia', 'Portugal'], correctAnswer: 0 },
      { question: 'Onde fica o Big Ben?', options: ['Londres', 'Paris', 'Nova Iorque', 'Sydney'], correctAnswer: 0 },
      { question: 'Qual país é famoso por tulipas?', options: ['Holanda', 'Bélgica', 'Dinamarca', 'Suíça'], correctAnswer: 0 },
      { question: 'Onde nasceu o futebol?', options: ['Inglaterra', 'Brasil', 'Alemanha', 'Itália'], correctAnswer: 0 },
      { question: 'Onde fica a Estátua da Liberdade?', options: ['Nova Iorque', 'Paris', 'Londres', 'Washington'], correctAnswer: 0 },
      { question: 'Quantos continentes existem?', options: ['5-7 (depende do modelo)', '4', '8', '3'], correctAnswer: 0 },
      { question: 'Qual é o maior oceano?', options: ['Pacífico', 'Atlântico', 'Índico', 'Ártico'], correctAnswer: 0 },
      { question: 'Qual é o maior continente?', options: ['Ásia', 'África', 'América', 'Europa'], correctAnswer: 0 },
      { question: 'Qual oceano separa Europa de América?', options: ['Atlântico', 'Pacífico', 'Índico', 'Ártico'], correctAnswer: 0 },
      { question: 'Qual é o rio mais longo?', options: ['Amazonas/Nilo', 'Mississípi', 'Yangtzé', 'Congo'], correctAnswer: 0 },
      { question: 'Onde fica a Floresta Amazónica?', options: ['América do Sul', 'África', 'Ásia', 'Oceânia'], correctAnswer: 0 },
      { question: 'Qual é a montanha mais alta?', options: ['Everest', 'K2', 'Kilimanjaro', 'Aconcágua'], correctAnswer: 0 },
      { question: 'Qual é o rio que passa por Paris?', options: ['Sena', 'Tâmisa', 'Danúbio', 'Reno'], correctAnswer: 0 },
      { question: 'Qual rio passa por Lisboa?', options: ['Tejo', 'Douro', 'Mondego', 'Guadiana'], correctAnswer: 0 },
      { question: 'O que é um vulcão?', options: ['Montanha que expele lava', 'Montanha normal', 'Vale', 'Planície'], correctAnswer: 0 },
      { question: 'O que é um arquipélago?', options: ['Conjunto de ilhas', 'Península', 'Continente', 'Oceano'], correctAnswer: 0 },
      { question: 'O que é latitude?', options: ['Distância ao Equador', 'Distância ao polo', 'Altitude', 'Longitude'], correctAnswer: 0 },
      { question: 'O que é altitude?', options: ['Altura em relação ao mar', 'Latitude', 'Longitude', 'Temperatura'], correctAnswer: 0 },
    ],
  } as TriviaCategory,

  atualidade: {
    label: '📰 Atualidade',
    questions: [
      { question: 'O que é um smartphone?', options: ['Telefone inteligente', 'Computador', 'Tablet', 'Relógio'], correctAnswer: 0 },
      { question: 'O que significa WiFi?', options: ['Internet sem fios', 'Rede de cabos', 'Antena', 'Satélite'], correctAnswer: 0 },
      { question: 'O que é Instagram?', options: ['Rede social de fotos', 'Motor de busca', 'Email', 'Jogo'], correctAnswer: 0 },
      { question: 'Quem fundou a Apple?', options: ['Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Elon Musk'], correctAnswer: 0 },
      { question: 'O que é um emoji?', options: ['Símbolo expressivo', 'Programa', 'Jogo', 'Website'], correctAnswer: 0 },
      { question: 'O que é streaming?', options: ['Transmissão online', 'Download', 'Upload', 'Gravação'], correctAnswer: 0 },
      { question: 'O que é o YouTube?', options: ['Plataforma de vídeos', 'Rede social', 'Jogo', 'Motor de busca'], correctAnswer: 0 },
      { question: 'O que significa app?', options: ['Aplicação', 'Apple', 'Internet', 'Programa de TV'], correctAnswer: 0 },
      { question: 'O que é cloud (nuvem)?', options: ['Armazenamento online', 'Meteorologia', 'Software', 'Hardware'], correctAnswer: 0 },
      { question: 'O que é um hashtag?', options: ['#etiqueta nas redes', 'Email', 'Website', 'Vírus'], correctAnswer: 0 },
      { question: 'O que é TikTok?', options: ['App de vídeos curtos', 'Relógio', 'Jogo', 'Motor de busca'], correctAnswer: 0 },
      { question: 'O que é um QR code?', options: ['Código de barras 2D', 'Senha', 'App', 'Vírus'], correctAnswer: 0 },
      { question: 'O que é Netflix?', options: ['Serviço de streaming', 'Rede social', 'Jogo', 'Motor de busca'], correctAnswer: 0 },
      { question: 'O que é Spotify?', options: ['Serviço de música', 'Rede social', 'Jogo', 'Vídeo'], correctAnswer: 0 },
      { question: 'O que é um podcast?', options: ['Programa de áudio online', 'Vídeo', 'Jogo', 'Foto'], correctAnswer: 0 },
      { question: 'Quem ganhou mais Bolas de Ouro?', options: ['Messi/Ronaldo', 'Pelé', 'Maradona', 'Zidane'], correctAnswer: 0 },
      { question: 'Quantos jogadores tem time de futebol?', options: ['11', '10', '12', '9'], correctAnswer: 0 },
      { question: 'De que cor é o cartão de expulsão?', options: ['Vermelho', 'Amarelo', 'Azul', 'Verde'], correctAnswer: 0 },
      { question: 'Quantos sets tem jogo de ténis?', options: ['3 ou 5', '2', '4', '6'], correctAnswer: 0 },
      { question: 'Qual desporto joga Ronaldo?', options: ['Futebol', 'Basquetebol', 'Ténis', 'Golfe'], correctAnswer: 0 },
      { question: 'Onde foram os Jogos Olímpicos 2016?', options: ['Rio de Janeiro', 'Londres', 'Pequim', 'Atenas'], correctAnswer: 0 },
      { question: 'Qual é o torneio de ténis em Londres?', options: ['Wimbledon', 'Roland Garros', 'US Open', 'Australian Open'], correctAnswer: 0 },
      { question: 'Qual desporto pratica Federer?', options: ['Ténis', 'Futebol', 'Basquetebol', 'Golfe'], correctAnswer: 0 },
      { question: 'Quantos jogadores tem equipa de basquetebol?', options: ['5 em campo', '6', '7', '11'], correctAnswer: 0 },
      { question: 'Qual a duração de jogo de futebol?', options: ['90 minutos', '80 minutos', '100 minutos', '120 minutos'], correctAnswer: 0 },
      { question: 'Quem canta Shape of You?', options: ['Ed Sheeran', 'Justin Bieber', 'Bruno Mars', 'Shawn Mendes'], correctAnswer: 0 },
      { question: 'Qual série tem Jon Snow?', options: ['Game of Thrones', 'Vikings', 'The Witcher', 'The Crown'], correctAnswer: 0 },
      { question: 'Qual saga tem Luke Skywalker?', options: ['Star Wars', 'Star Trek', 'Harry Potter', 'Senhor dos Anéis'], correctAnswer: 0 },
      { question: 'Quem interpreta Homem-Aranha (atual)?', options: ['Tom Holland', 'Tobey Maguire', 'Andrew Garfield', 'Chris Evans'], correctAnswer: 0 },
      { question: 'Qual série tem Eleven?', options: ['Stranger Things', 'Dark', 'The Umbrella Academy', 'Westworld'], correctAnswer: 0 },
      { question: 'Quem canta Rolling in the Deep?', options: ['Adele', 'Beyoncé', 'Rihanna', 'Taylor Swift'], correctAnswer: 0 },
      { question: 'Quem é o rei do pop?', options: ['Michael Jackson', 'Elvis', 'Madonna', 'Prince'], correctAnswer: 0 },
      { question: 'Qual banda cantava Bohemian Rhapsody?', options: ['Queen', 'Beatles', 'Rolling Stones', 'Led Zeppelin'], correctAnswer: 0 },
      { question: 'Quem é a rainha do pop?', options: ['Madonna', 'Beyoncé', 'Lady Gaga', 'Rihanna'], correctAnswer: 0 },
      { question: 'Qual série tem Walter White?', options: ['Breaking Bad', 'Better Call Saul', 'The Wire', 'Narcos'], correctAnswer: 0 },
      { question: 'Quem interpreta Iron Man?', options: ['Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'], correctAnswer: 0 },
      { question: 'O que é aquecimento global?', options: ['Aumento temperatura Terra', 'Arrefecimento', 'Chuva ácida', 'Camada ozono'], correctAnswer: 0 },
      { question: 'O que são energias renováveis?', options: ['Que se renovam', 'Petróleo', 'Carvão', 'Gás'], correctAnswer: 0 },
      { question: 'O que é reciclagem?', options: ['Reutilizar materiais', 'Queimar lixo', 'Enterrar', 'Exportar'], correctAnswer: 0 },
      { question: 'O que é COVID-19?', options: ['Doença causada por coronavírus', 'Gripe', 'Constipação', 'Alergia'], correctAnswer: 0 },
      { question: 'O que é uma vacina?', options: ['Previne doenças', 'Cura doenças', 'Analgésico', 'Antibiótico'], correctAnswer: 0 },
      { question: 'O que é isolamento?', options: ['Ficar separado', 'Festa', 'Viagem', 'Trabalho'], correctAnswer: 0 },
      { question: 'O que é democracia?', options: ['Poder do povo', 'Ditadura', 'Monarquia', 'Anarquia'], correctAnswer: 0 },
      { question: 'O que é ONU?', options: ['Organização Nações Unidas', 'Exército', 'Empresa', 'Partido'], correctAnswer: 0 },
      { question: 'O que é União Europeia?', options: ['União de países europeus', 'País', 'Cidade', 'Continente'], correctAnswer: 0 },
      { question: 'Qual moeda da União Europeia?', options: ['Euro', 'Dólar', 'Libra', 'Franco'], correctAnswer: 0 },
    ],
  } as TriviaCategory,
};

export const categoryLabels = {
  ciencia: triviaCategories.ciencia.label,
  culturaArte: triviaCategories.culturaArte.label,
  literatura: triviaCategories.literatura.label,
  historia: triviaCategories.historia.label,
  geografia: triviaCategories.geografia.label,
  atualidade: triviaCategories.atualidade.label,
};
