export const quemSouEuCategories = {
  'actoresPT': [
    'Herman José', 'Cristina Ferreira', 'Manuel Luís Goucha', 'Fátima Lopes',
    'Ricardo Araújo Pereira', 'César Mourão', 'Nuno Markl', 'Vasco Palmeirim',
    'Filomena Cautela', 'Rui Unas', 'Daniela Ruah', 'Diogo Morgado',
    'Rita Pereira', 'Pedro Teixeira', 'Cláudia Vieira', 'João Baião',
    'Júlia Pinheiro', 'Fernando Mendes', 'José Carlos Malato', 'Catarina Furtado',
    'Jorge Gabriel', 'Tânia Ribas de Oliveira', 'Sara Matos', 'Lourenço Ortigão',
    'Kelly Bailey', 'Jessica Athayde', 'Bruno Nogueira', 'Salvador Martinha',
    'João Manzarra', 'Diana Chaves', 'Luciana Abreu', 'Ruy de Carvalho',
    'Eunice Muñoz', 'Nicolau Breyner', 'Camilo de Oliveira', 'Maria Rueff',
    'Joaquim de Almeida', 'Albano Jerónimo', 'Nuno Lopes', 'Pêpê Rapazote',
    'Carolina Patrocínio', 'Lili Caneças', 'José Castelo Branco', 'Teresa Guilherme',
    'Cláudio Ramos', 'Pipoca Mais Doce', 'Ljubomir Stanisic', 'Toy',
    'Quim Barreiros', 'Ágata', 'Marco Paulo', 'Emanuel', 'José Cid',
    'Fernando Rocha', 'Beatriz Gosta', 'Bumba na Fofinha', 'António Raminhos',
    'Eduardo Madeira', 'Joana Marques', 'Ana Guiomar', 'Pedro Granger'
  ],
  'actoresInt': [
    'Brad Pitt', 'Angelina Jolie', 'Leonardo DiCaprio', 'Tom Cruise',
    'Johnny Depp', 'Will Smith', 'Meryl Streep', 'Julia Roberts',
    'George Clooney', 'Jennifer Aniston', 'Dwayne "The Rock" Johnson', 'Kevin Hart',
    'Sandra Bullock', 'Robert De Niro', 'Al Pacino', 'Morgan Freeman',
    'Tom Hanks', 'Nicole Kidman', 'Scarlett Johansson', 'Ryan Reynolds',
    'Margot Robbie', 'Emma Watson', 'Daniel Radcliffe', 'Chris Hemsworth',
    'Chris Evans', 'Robert Downey Jr.', 'Vin Diesel', 'Jason Statham',
    'Cameron Diaz', 'Jim Carrey', 'Adam Sandler', 'Eddie Murphy',
    'Rowan Atkinson (Mr. Bean)', 'Jackie Chan', 'Bruce Willis', 'Arnold Schwarzenegger',
    'Sylvester Stallone', 'Keanu Reeves', 'Matt Damon', 'Ben Affleck',
    'Jennifer Lawrence', 'Anne Hathaway', 'Charlize Theron', 'Hugh Jackman',
    'Henry Cavill', 'Zendaya', 'Timothée Chalamet', 'Pedro Pascal',
    'Jenna Ortega', 'Kim Kardashian', 'Kylie Jenner', 'Paris Hilton',
    'Príncipe Harry', 'Meghan Markle', 'Rainha Isabel II', 'Papa Francisco',
    'Donald Trump', 'Barack Obama', 'Elon Musk', 'Mark Zuckerberg',
    'Oprah Winfrey', 'Ellen DeGeneres'
  ],
  'musica': [
    'Amália Rodrigues', 'Mariza', 'Ana Moura', 'Camané', 'Salvador Sobral',
    'Luísa Sobral', 'Rui Veloso', 'Jorge Palma', 'Xutos & Pontapés', 'GNR',
    'Ornatos Violeta', 'Da Weasel', 'Buraka Som Sistema', 'The Gift',
    'Capitão Fausto', 'D.A.M.A', 'Calema', 'Diogo Piçarra', 'Carolina Deslandes',
    'Aurea', 'Marisa Liz', 'Agir', 'Bárbara Bandeira', 'Wet Bed Gang',
    'Richie Campbell', 'Tony Carreira', 'Mickael Carreira', 'David Carreira',
    'Anselmo Ralph', 'Ivete Sangalo', 'Anitta', 'Roberto Carlos', 'Caetano Veloso',
    'Madonna', 'Michael Jackson', 'Beyoncé', 'Rihanna', 'Taylor Swift',
    'Lady Gaga', 'Adele', 'Ed Sheeran', 'Justin Bieber', 'Harry Styles',
    'Dua Lipa', 'Billie Eilish', 'Bruno Mars', 'The Beatles', 'Queen',
    'The Rolling Stones', 'U2', 'Coldplay', 'Nirvana', 'Metallica',
    'AC/DC', 'Pink Floyd', 'ABBA', 'Spice Girls', 'Backstreet Boys',
    'Britney Spears', 'Shakira', 'Jennifer Lopez', 'Eminem', 'Snoop Dogg',
    'Jay-Z', 'Drake', 'The Weeknd', 'Ariana Grande', 'Miley Cyrus',
    'Elton John', 'Freddie Mercury', 'Elvis Presley', 'Frank Sinatra', 'Bob Marley'
  ],
  'personagens': [
    'Rato Mickey', 'Pato Donald', 'Tio Patinhas', 'Minnie', 'Pateta', 'Pluto',
    'Popeye', 'Bugs Bunny', 'Tom & Jerry', 'Tweety', 'Silvestre', 'SpongeBob',
    'Patrick Estrela', 'Dora a Exploradora', 'Noddy', 'Bombeiro Sam',
    'Ovelha Choné', 'Porquinha Peppa', 'Patrulha Pata', 'Super Mario', 'Luigi',
    'Pikachu', 'Sonic', 'Harry Potter', 'Hermione Granger', 'Ron Weasley',
    'Voldemort', 'Dumbledore', 'Frodo Baggins', 'Gandalf', 'Gollum',
    'Luke Skywalker', 'Darth Vader', 'Yoda', 'Princesa Leia', 'Han Solo',
    'Chewbacca', 'Homem-Aranha', 'Super-Homem', 'Batman', 'Joker',
    'Mulher Maravilha', 'Hulk', 'Capitão América', 'Thor', 'Homem de Ferro',
    'Thanos', 'Elsa (Frozen)', 'Anna (Frozen)', 'Olaf', 'Cinderela',
    'Branca de Neve', 'A Pequena Sereia', 'Bela (Bela e o Monstro)', 'Tarzan',
    'Simba (Rei Leão)', 'Shrek', 'Burro (Shrek)', 'Gru (Mínimos)', 'Minions',
    'Zé Povinho', 'Capuchinho Vermelho', 'Lobo Mau', 'Pinóquio', 'Peter Pan',
    'Sininho', 'James Bond', 'Sherlock Holmes', 'Dracula', 'Frankenstein',
    'Pai Natal', 'Coelhinho da Páscoa', 'Fada dos Dentes', 'Bruxa', 'Feiticeiro',
    'Fada', 'Sereia', 'Vampiro', 'Lobisomem', 'Múmia', 'Fantasma', 'Zombie',
    'Super-Herói', 'Robô', 'Extraterrestre'
  ],
  'desporto': [
    'Cristiano Ronaldo', 'Lionel Messi', 'Eusébio', 'Luís Figo', 'José Mourinho',
    'Pepe', 'Bernardo Silva', 'Bruno Fernandes', 'João Félix', 'Rúben Dias',
    'Sérgio Conceição', 'Rúben Amorim', 'Jorge Jesus', 'Pinto da Costa',
    'Frederico Varandas', 'Rui Costa', 'Iker Casillas', 'Neymar', 'Mbappé',
    'Haaland', 'Maradona', 'Pelé', 'Beckham', 'Zidane', 'Ronaldinho Gaúcho',
    'Fernando Alonso', 'Lewis Hamilton', 'Max Verstappen', 'Ayrton Senna',
    'Michael Schumacher', 'Miguel Oliveira (MotoGP)', 'Telma Monteiro',
    'Fernando Pimenta', 'Pichardo', 'Nelson Évora', 'Rosa Mota', 'Carlos Lopes',
    'Fernanda Ribeiro', 'Rafael Nadal', 'Roger Federer', 'Novak Djokovic',
    'Serena Williams', 'Michael Jordan', 'LeBron James', 'Kobe Bryant',
    'Tiger Woods', 'Usain Bolt', 'Simone Biles', 'Benfica', 'Sporting', 'Porto',
    'Seleção Nacional', 'Estádio da Luz', 'Estádio do Dragão', 'Estádio de Alvalade'
  ],
  'animais': [
    'Cão', 'Gato', 'Rato', 'Hamster', 'Coelho', 'Porquinho-da-índia', 'Piriquito',
    'Papagaio', 'Canário', 'Peixe-dourado', 'Tartaruga', 'Cágado', 'Cavalo',
    'Pónei', 'Burro', 'Vaca', 'Boi', 'Touro', 'Ovelha', 'Cabra', 'Porco',
    'Galinha', 'Galo', 'Pinto', 'Pato', 'Ganso', 'Peru', 'Avestruz', 'Leão',
    'Tigre', 'Leopardo', 'Chita', 'Jaguar', 'Pantera', 'Lobo', 'Raposa',
    'Urso', 'Urso Polar', 'Panda', 'Elefante', 'Girafa', 'Hipopótamo',
    'Rinoceronte', 'Zebra', 'Macaco', 'Gorila', 'Chimpanzé', 'Canguru', 'Coala',
    'Preguiça', 'Lémure', 'Suricata', 'Camelo', 'Dromedário', 'Lama', 'Esquilo',
    'Ouriço-cacheiro', 'Morcego', 'Cobra', 'Lagarto', 'Crocodilo', 'Jacaré',
    'Camaleão', 'Sapo', 'Rã', 'Salamandra', 'Tubarão', 'Baleia', 'Golfinho',
    'Foca', 'Leão-marinho', 'Pinguim', 'Polvo', 'Lula', 'Caranguejo', 'Lagosta',
    'Camarão', 'Cavalo-marinho', 'Estrela-do-mar', 'Medusa', 'Águia', 'Falcão',
    'Coruja', 'Mocho', 'Cegonha', 'Gaivota', 'Pombo', 'Pardal', 'Andorinha',
    'Corvo', 'Flamingo', 'Pavão', 'Cisne', 'Borboleta', 'Abelha', 'Vespa',
    'Mosca', 'Mosquito', 'Formiga', 'Barata', 'Aranha', 'Escorpião', 'Grilo',
    'Gafanhoto', 'Minhoca', 'Caracol', 'Lesma', 'Lince Ibérico', 'Javali',
    'Sardinha', 'Bacalhau (o peixe)', 'Veado', 'Abutre', 'Lontra', 'Castor',
    'Morsa', 'Melga', 'Joaninha', 'Dinossauro', 'Dragão', 'Unicórnio'
  ],
  'comidaBebida': [
    'Bacalhau à Brás', 'Bacalhau com Natas', 'Cozido à Portuguesa', 'Feijoada',
    'Caldo Verde', 'Canja de Galinha', 'Sopa da Pedra', 'Francesinha',
    'Tripas à Moda do Porto', 'Leitão da Bairrada', 'Carne de Porco à Alentejana',
    'Sardinha Assada', 'Polvo à Lagareiro', 'Arroz de Pato', 'Arroz de Marisco',
    'Açorda', 'Migas', 'Alheira', 'Chouriço', 'Morcela', 'Queijo da Serra',
    'Pastel de Nata', 'Bola de Berlim', 'Travesseiro de Sintra', 'Ovos Moles',
    'Pão de Ló', 'Arroz Doce', 'Leite Creme', 'Mousse de Chocolate', 'Gelatina',
    'Salame de Chocolate', 'Croissant', 'Pão com Chouriço', 'Tosta Mista',
    'Prego no Pão', 'Bifana', 'Hambúrguer', 'Pizza', 'Sushi', 'Lasanha',
    'Esparguete à Bolonhesa', 'Risoto', 'Kebab', 'Taco', 'Burrito', 'Batatas Fritas',
    'Pipocas', 'Chocolate', 'Gelado', 'Iogurte', 'Leite', 'Café', 'Bica',
    'Galão', 'Meia-de-leite', 'Chá', 'Sumo de Laranja', 'Compal', 'Coca-Cola',
    'Ice Tea', 'Cerveja', 'Vinho do Porto', 'Vinho Verde', 'Ginjinha', 'Poncha',
    'Água', 'Azeitonas', 'Tremoços', 'Amendoins', 'Maçã', 'Banana', 'Laranja',
    'Morango', 'Melancia', 'Uvas', 'Cenoura', 'Milho', 'Ovo', 'Queijo', 'Pão',
    'Cachorro-quente', 'Esparguete', 'Bolo', 'Bolacha', 'Donut', 'Rebuçado',
    'Sopa', 'Leitão', 'Bife', 'Frango Assado', 'Salsicha', 'Presunto', 'Manteiga',
    'Compota', 'Mel', 'Cereais', 'Panqueca', 'Salada', 'Tomate', 'Alface',
    'Pepino', 'Cebola', 'Alho', 'Batata', 'Brócolos', 'Cogumelos', 'Pêra',
    'Pêssego', 'Ananás', 'Cereja', 'Kiwi', 'Limão', 'Coco', 'Noz', 'Pudim',
    'Pastilha Elástica'
  ],
  'filmesTV': [
    'Titanic', 'O Padrinho', 'Star Wars', 'O Senhor dos Anéis', 'Harry Potter',
    'Velocidade Furiosa', 'Missão Impossível', '007 James Bond', 'Sozinho em Casa',
    'Shrek', 'Toy Story', 'O Rei Leão', 'Frozen', 'Mamma Mia', 'Grease',
    'Dirty Dancing', 'Pretty Woman', 'Top Gun', 'Avatar', 'Jurassic Park',
    'Tubarão', 'Psycho', 'O Exorcista', 'Friends', 'A Teoria do Big Bang',
    'Anatomia de Grey', 'Guerra dos Tronos', 'Breaking Bad', 'La Casa de Papel',
    'Stranger Things', 'Squid Game', 'The Crown', 'Black Mirror', 'Os Simpsons',
    'Family Guy', 'South Park', 'Morangos com Açúcar', 'Big Brother',
    'Casa dos Segredos', 'O Preço Certo', 'Ídolos', 'The Voice Portugal',
    'Got Talent Portugal', 'Jornal da Noite', 'Telejornal', 'Rua Sésamo',
    'Batatoon', 'Levanta-te e Ri', 'Malucos do Riso', 'Inspetor Max',
    'Conta-me Como Foi'
  ],
  'objetos': [
    'Telemóvel', 'Computador', 'Tablet', 'Televisão', 'Comando', 'Sofá', 'Cama',
    'Almofada', 'Lençol', 'Cobertor', 'Mesa', 'Cadeira', 'Candeeiro', 'Armário',
    'Espelho', 'Tapete', 'Cortina', 'Janela', 'Porta', 'Chave', 'Relógio',
    'Óculos', 'Óculos de Sol', 'Chapéu', 'Boné', 'Cachecol', 'Luvas', 'Casaco',
    'Calças', 'Camisola', 'T-shirt', 'Vestido', 'Saia', 'Sapatos', 'Ténis',
    'Chinelos', 'Botas', 'Meias', 'Cuecas', 'Soutien', 'Pijama', 'Escova de Dentes',
    'Pasta de Dentes', 'Sabonete', 'Champô', 'Papel Higiénico', 'Toalha', 'Pente',
    'Secador', 'Maquilhagem', 'Batom', 'Perfume', 'Tesoura', 'Faca', 'Garfo',
    'Colher', 'Prato', 'Copo', 'Caneca', 'Panela', 'Frigideira', 'Forno',
    'Microondas', 'Frigorífico', 'Máquina de Lavar', 'Vassoura', 'Esfregona',
    'Balde', 'Lixo', 'Caneta', 'Lápis', 'Borracha', 'Caderno', 'Livro', 'Mochila',
    'Carteira', 'Dinheiro', 'Cartão de Cidadão', 'Guarda-chuva', 'Mala de Viagem',
    'Carro', 'Mota', 'Bicicleta', 'Trotinete', 'Autocarro', 'Comboio', 'Avião',
    'Barco', 'Guitarra', 'Violino', 'Flauta', 'Tambor', 'Pandeireta', 'Apito',
    'Telefone', 'Presente / Prenda', 'Caixote do Lixo', 'Camião', 'Helicóptero',
    'Bola', 'Árvore', 'Flor', 'Sol', 'Lua', 'Estrela', 'Nuvem', 'Arco-íris',
    'Boneco de Neve', 'Jornal', 'Carta (Correio)', 'Skate', 'Semáforo'
  ],
  'acoes': [
    'Dormir', 'Comer', 'Beber', 'Correr', 'Saltar', 'Nadar', 'Dançar', 'Cantar',
    'Gritar', 'Chorar', 'Rir', 'Espirrar', 'Tossir', 'Bocejar', 'Escrever', 'Ler',
    'Pintar', 'Desenhar', 'Cozinhar', 'Lavar a Loiça', 'Varrer', 'Passar a Ferro',
    'Conduzir', 'Andar de Bicicleta', 'Jogar Futebol', 'Jogar Ténis', 'Boxear',
    'Pescar', 'Caçar', 'Disparar', 'Morrer (fazer de morto)', 'Nascer', 'Casar',
    'Pedir em Casamento', 'Abraçar', 'Beijar', 'Cumprimentar', 'Acenar', 'Aplaudir',
    'Assobiar', 'Tocar Guitarra', 'Tocar Piano', 'Tocar Bateria', 'Tocar Violino',
    'Tocar Trompete', 'Atar os Sapatos', 'Vestir', 'Despir', 'Tomar Banho',
    'Lavar os Dentes', 'Pentear', 'Maquilhar', 'Cortar o Cabelo', 'Fazer a Barba',
    'Tirar uma Selfie', 'Falar ao Telemóvel', 'Enviar uma Mensagem', 'Jogar Computador',
    'Ver Televisão', 'Mudar a Lâmpada', 'Pregar um Prego', 'Serrar', 'Cavar',
    'Regar', 'Cortar a Relva', 'Passear o Cão', 'Dar Biberão', 'Mudar a Fralda',
    'Fumar', 'Acender um Fósforo', 'Soprar Velas', 'Abrir um Presente',
    'Encher um Balão', 'Voar (como pássaro)', 'Rastejar', 'Escalar', 'Mergulhar',
    'Surf', 'Skate', 'Esquiar', 'Patinar'
  ],
  'lugares': [
    'Portugal', 'Espanha', 'França', 'Inglaterra', 'Itália', 'Alemanha', 'Brasil',
    'Estados Unidos', 'China', 'Japão', 'Austrália', 'Lisboa', 'Porto', 'Algarve',
    'Madeira', 'Açores', 'Serra da Estrela', 'Torre Eiffel', 'Estátua da Liberdade',
    'Muralha da China', 'Pirâmides do Egito', 'Coliseu de Roma', 'Big Ben',
    'Disneylândia', 'Hollywood', 'McDonald\'s', 'Burger King', 'KFC', 'Pizza Hut',
    'Starbucks', 'Nespresso', 'Delta Cafés', 'Olá (gelados)', 'Sumol', 'Compal',
    'Mimosa', 'Continente', 'Pingo Doce', 'Lidl', 'IKEA', 'Zara', 'Primark',
    'H&M', 'Nike', 'Adidas', 'Puma', 'Apple', 'Samsung', 'PlayStation', 'Nintendo',
    'YouTube', 'Google', 'Facebook', 'Instagram', 'TikTok', 'WhatsApp', 'Netflix',
    'Spotify', 'Mercedes', 'BMW', 'Ferrari', 'Tesla', 'TAP (Air Portugal)',
    'Uber', 'Glovo'
  ],
  'profissoes': [
    'Polícia', 'Bombeiro', 'Médico', 'Professor(a)', 'Cozinheiro', 'Astronauta',
    'Palhaço', 'Pirata', 'Rei / Rainha', 'Enfermeiro', 'Dentista', 'Veterinário',
    'Farmacêutico', 'Padeiro', 'Talhante', 'Peixeiro', 'Agricultor', 'Jardineiro',
    'Carpinteiro', 'Canalizador', 'Eletricista', 'Pintor', 'Mecânico', 'Motorista',
    'Piloto de Avião', 'Hospedeira de Bordo', 'Carteiro', 'Jornalista', 'Fotógrafo',
    'Cantor', 'Bailarino', 'Ator', 'Mágico', 'Futebolista', 'Nadador-salvador',
    'Juiz', 'Advogado', 'Padre', 'Presidente', 'Ladrão', 'Espião', 'Detetive',
    'Cowboy', 'Índio', 'Ninja', 'Samurai', 'Viking'
  ]
};

export const categoryLabels: Record<keyof typeof quemSouEuCategories, string> = {
  actoresPT: '🇵🇹 Actores e Personalidades',
  actoresInt: '🌍 Actores e Celebridades',
  musica: '🎵 Música',
  personagens: '🧙 Personagens Fictícias',
  desporto: '⚽ Desporto',
  animais: '🦁 Animais',
  comidaBebida: '🍳 Comida e Bebida',
  filmesTV: '🎬 Filmes e TV',
  objetos: '🏠 Objetos e Coisas',
  acoes: '🏃 Ações (Verbos)',
  lugares: '🗺️ Lugares e Marcas',
  profissoes: '👮 Profissões'
};
